name: npm install workflow

on: [push, pull_request]

jobs:
  my-job:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: hcho3
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: hello-world
